version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    restart: always
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: changeme
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    restart: always
    environment:  
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: "true"
    ports:
    - "5601:5601"
    depends_on:
     - elasticsearch

# On Kibana / dev tools, execute following

# GET test_dataflow/_search
# {
#   "query": {
#     "match_all": {}
#   }
# }